config/routes.rb
Rails.application.routes.draw do
  resources :player_actions

end

app/models/player_action.rb
class PlayerAction < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/player_actions_controller.rb
class PlayerActionsController < ApplicationController
  before_action :set_player_action, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :create # TODO - Add some type of protection for create (like a real REST API)

  # GET /player_actions
  # GET /player_actions.json
  def index
    @player_actions = PlayerAction.all
  end

  # GET /player_actions/1
  # GET /player_actions/1.json
  def show
  end

  # GET /player_actions/new
  def new
    @player_action = PlayerAction.new
  end

  # GET /player_actions/1/edit
  def edit
  end

  # POST /player_actions
  # POST /player_actions.json
  def create
    @player_action = PlayerAction.new(player_action_params)

    respond_to do |format|
      if @player_action.save
        format.html { redirect_to @player_action, notice: 'Player action was successfully created.' }
        format.json { render :show, status: :created, location: @player_action }
      else
        format.html { render :new }
        format.json { render json: @player_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_actions/1
  # PATCH/PUT /player_actions/1.json
  def update
    respond_to do |format|
      if @player_action.update(player_action_params)
        format.html { redirect_to @player_action, notice: 'Player action was successfully updated.' }
        format.json { render :show, status: :ok, location: @player_action }
      else
        format.html { render :edit }
        format.json { render json: @player_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_actions/1
  # DELETE /player_actions/1.json
  def destroy
    @player_action.destroy
    respond_to do |format|
      format.html { redirect_to player_actions_url, notice: 'Player action was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_action
      @player_action = PlayerAction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_action_params
      params.require(:player_action).permit(:name, :position)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/player_actions_helper.rb
module PlayerActionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JsonTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/player_actions/_form.html.erb
<%= form_for(@player_action) do |f| %>
  <% if @player_action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player_action.errors.count, "error") %> prohibited this player_action from being saved:</h2>

      <ul>
      <% @player_action.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/player_actions/edit.html.erb
<h1>Editing player_action</h1>

<%= render 'form' %>

<%= link_to 'Show', @player_action %> |
<%= link_to 'Back', player_actions_path %>

app/views/player_actions/index.html.erb
<h1>Listing player_actions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @player_actions.each do |player_action| %>
      <tr>
        <td><%= player_action.name %></td>
        <td><%= player_action.position %></td>
        <td><%= link_to 'Show', player_action %></td>
        <td><%= link_to 'Edit', edit_player_action_path(player_action) %></td>
        <td><%= link_to 'Destroy', player_action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player action', new_player_action_path %>

app/views/player_actions/new.html.erb
<h1>New player_action</h1>

<%= render 'form' %>

<%= link_to 'Back', player_actions_path %>

app/views/player_actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player_action.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @player_action.position %>
</p>

<%= link_to 'Edit', edit_player_action_path(@player_action) %> |
<%= link_to 'Back', player_actions_path %>